### ISSUE TITLE
What's the k value setting?

### ISSUE THREAD

**Issue by Jiawei0o0** [GuoleiSun/HNC_loss#1]
Thanks for your great job.
I am confused about the K value in the TopK function.  I can't find the setting in your paper. Does it make sense to the result?
Waiting for your reply. Thanks a lot!

**Comment by GuoleiSun** [comment]
Hi,

Thanks for your interest. K value means that the CAMs of top-k negative classes will be suppressed. The code is here https://github.com/GuoleiSun/HNC_loss/blob/5d44b504e68a7bcbecd59a738b8816f233d93dfa/imagenet/train_imagenet_cam_loss.py#L81

It makes sense to the result and is a hyper parameter. For ImageNet, we set k as 100.
