### ISSUE TITLE
multi-label classification question

### ISSUE THREAD

**Issue by Jiawei0o0** [GuoleiSun/HNC_loss#2]
Thanks for your great job again.
Can the code work well in the multi-label classification situation?
[https://github.com/GuoleiSun/HNC_loss/blob/5d67612cb52780cc04d63344ee6c6672e3ef2a4b/imagenet/train_imagenet_cam_loss.py#L65](URL)
or some change needs to be done?

**Comment by GuoleiSun** [comment]
Hello,
Thanks for your interest. Depends on your dataset, you may need to tune k value (set to be 100 for imagenet in our code) and the weight of our loss (lambda in the paper).
